name: Node Versions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and format
        run: |
          make frontend-install
          make frontend-format
      - name: Lint
        run: |
          make frontend-lint
      - name: Test
        run: |
          make frontend-test